# Generated by Django 4.2.28 on 2026-02-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_statetransition_teammember_teamproject_issueproperty_issuepropertyvalue_issuetemplate_projecttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='issuepropertyvalue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='issuetemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterUniqueTogether(
            name='issueproperty',
            unique_together={('workspace', 'issue_type', 'name', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='issuepropertyvalue',
            unique_together={('issue', 'property', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='issuetemplate',
            unique_together={('workspace', 'project', 'name', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttemplate',
            unique_together={('workspace', 'name', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='statetransition',
            unique_together={('project', 'from_state', 'to_state', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='teamproject',
            unique_together={('team', 'project', 'deleted_at')},
        ),
    ]
